apiVersion: v1
kind: Service
metadata:
  name: user_service
spec:
  type: NodePort
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
      nodePort: 30011