apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-queue
  labels:
    app: payment-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-queue
  template:
    metadata:
      labels:
        app: payment-queue
    spec:
      containers:
      - name: payment-queue
        image: sshobha379/payment-queue:v1
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi
        envFrom:
          - configMapRef:
              name: mysql-config