apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30009