apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-routes
  labels:
    app: bus-routes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bus-routes
  template:
    metadata:
      labels:
        app: bus-routes
    spec:
      containers:
      - name: bus-routes
        image: sshobha379/bus-routes:v1
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi
        envFrom:
          - configMapRef:
              name: mysql-config