kind: Service
metadata:
  name: booking
spec:
  externalIPs:
  - 172.31.23.18
  type: LoadBalancer
  selector:
    app: booking
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003