apiVersion: v1
kind: Service
metadata:
  name: booking
spec:
  type: NodePort
  selector:
    app: booking
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30010