apiVersion: v1
kind: Service
metadata:
  name: bus-routes
spec:
  type: NodePort
  selector:
    app: bus-routes
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007